title: Qlibs++
url: https://qlibs.github.io
description: "Modern C++ libraries"

color:
  primary-dark: '#000000'
  links: '#219ab3'

footer: Qlibs++

social:
  - title: github
    url: https://github.com/qlibs

markdown: kramdown
permalink: pretty
