title: Qlibs++
url: https://qlibs.github.io
description: "Mission: Quality, Performance, Simplicity"

color:
  primary-dark: '#000000'
  links: '#219ab3'

social:
  - title: github
    url: https://github.com/qlibs

markdown: kramdown
permalink: pretty
